server:
  port: ${PORT:0}   # puerto din√°mico (muy recomendado)

spring:
  application:
    name: operador-service
# http://localhost:8761/eureka
eureka:
  client:
    service-url:
      defaultZone: https://secure-appreciation-production-cf60.up.railway.app/eureka
    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: false
    hostname: magnificent-endurance-production-1de6.up.railway.app
    secure-port-enabled: true
    secure-port: 443
    metadata-map:
      protocol: https
      public-domain: magnificent-endurance-production-1de6.up.railway.app
