
#http://localhost:8761/eureka 
#http://eureka-server:8761/eureka
server:
  port: ${PORT}

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      routes:
        - id: operador-service
          uri: http://magnificent-endurance-production-1de6.up.railway.app
          predicates:
            - Path=/operador-service/**
          filters:
            - StripPrefix=1
            - AddResponseHeader=Access-Control-Allow-Origin, https://unir-biblioteca.vercel.app
            - AddResponseHeader=Access-Control-Allow-Headers, *
            - AddResponseHeader=Access-Control-Allow-Credentials, true

        - id: buscador-service
          uri: http://creative-trust-production-189b.up.railway.app
          predicates:
            - Path=/buscador-service/**
          filters:
            - StripPrefix=1
            - AddResponseHeader=Access-Control-Allow-Origin, https://unir-biblioteca.vercel.app
            - AddResponseHeader=Access-Control-Allow-Headers, *
            - AddResponseHeader=Access-Control-Allow-Credentials, true
            
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - https://unir-biblioteca.vercel.app
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders:
              - "*"
            allowCredentials: true

#default-filters:
#  - CircuitBreaker=name=default
#  - Retry

eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: https://secure-appreciation-production-cf60.up.railway.app/eureka
  instance:
      prefer-ip-address: false
      hostname: tarea3-unir-prod-production.up.railway.app