
#http://localhost:8761/eureka 
#http://eureka-server:8761/eureka
server:
  port: ${PORT:0}

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: operador-service
          uri: https://magnificent-endurance-production-1de6.up.railway.app
          predicates:
            - Path=/operador-service/**
          filters:
            - StripPrefix=1

        - id: buscador-service
          uri: https://creative-trust-production-189b.up.railway.app
          predicates:
            - Path=/buscador-service/**
          filters:
            - StripPrefix=1

      # fallback para evitar 404 en root
      default-filters:
        - CircuitBreaker=name=default
        - Retry

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: https://secure-appreciation-production-cf60.up.railway.app/eureka
