
#http://localhost:8761/eureka 
#http://eureka-server:8761/eureka
server:
  port: ${PORT}

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: operador-service
          uri: http://magnificent-endurance-production-1de6.up.railway.app
          predicates:
            - Path=/operador-service/**
          filters:
            - StripPrefix=1

        - id: buscador-service
          uri: http://creative-trust-production-189b.up.railway.app
          predicates:
            - Path=/buscador-service/**
          filters:
            - StripPrefix=1

#default-filters:
#  - CircuitBreaker=name=default
#  - Retry

eureka:
  client:
    enabled: false