
#http://localhost:8761/eureka
#http://eureka-server:8761/eureka
server:
  port: ${PORT:0}

spring:
  application:
    name: buscador-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: https://secure-appreciation-production-cf60.up.railway.app/eureka

  instance:
    hostname: creative-trust-production-189b.up.railway.app
    secure-port-enabled: true
    secure-port: 443
    prefer-ip-address: false

elasticsearch:
  url: https://bold-beech-1km27sfb.us-east-1.bonsaisearch.net
  index: libros
  username: b10e80ad9f
  password: 077629bad8cb60bb29dc