server:
  port: ${PORT:0}   # puerto din√°mico (muy recomendado)

spring:
  application:
    name: buscador-service
#http://localhost:8761/eureka
#http://eureka-server:8761/eureka
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
  instance:
    prefer-ip-address: true
