
#http://localhost:8761/eureka
#http://eureka-server:8761/eureka
server:
  port: ${PORT:0}

spring:
  application:
    name: buscador-service

eureka:
  client:
    service-url:
      defaultZone: https://secure-appreciation-production-cf60.up.railway.app/eureka
    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: false
    hostname: creative-trust-production-189b.up.railway.app
    secure-port-enabled: true
    secure-port: 443
    metadata-map:
      protocol: https
      public-domain: creative-trust-production-189b.up.railway.app



    