server:
  port: ${PORT:0}   # puerto din√°mico (muy recomendado)

spring:
  application:
    name: operador-service
# http://localhost:8761/eureka
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL}

  instance:
    prefer-ip-address: true
    secure-port-enabled: true
    secure-port: 443
    metadata-map:
      public-host: ${RAILWAY_PUBLIC_DOMAIN}
      public-protocol: https
      public-port: 443
