server:
  port: ${PORT:0}

spring:
  application:
    name: operador-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: https://secure-appreciation-production-cf60.up.railway.app/eureka

  instance:
    hostname: magnificent-endurance-production-1de6.up.railway.app
    secure-port-enabled: true
    secure-port: 443
    prefer-ip-address: false
