server:
  port: 0   # puerto din√°mico (muy recomendado)

spring:
  application:
    name: operador-service
# http://localhost:8761/eureka
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
  instance:
    prefer-ip-address: true
